[theme]
base = "light"
primaryColor = "#0E5EA6"
backgroundColor = "#F8F8F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E2938"
font = "sans serif"
borderColor = "#DCE1E7"
showWidgetBorder = true
